"""
Run dictionaries for parametric studies.
Each dictionary entry represents a set of parameters to modify from the base inputs.
Generated by Parametric_GUI
"""
import numpy as np

# Default run with base inputs
all_runs = [
    {
        "description": "Default inputs"
    }

    # Simple parameter runs
    ,{
        "description": "core_power = 10.0",
        "core_power": 10.0
    }
    ,{
        "description": "core_power = 20.0",
        "core_power": 20.0
    }
    ,{
        "description": "core_power = 20.0 + fuel_height = 0.5",
        "core_power": 20.0,
        "fuel_height": 0.5
    }
]

# Multi-parameter loops
# Generate parametric combinations automatically
# Loop set 1: Loop Set 1
loop_set_1_params = {
    "core_lattice": [[['C', 'F', 'F', 'C'], ['F', 'F', 'I_1', 'F'], ['F', 'F', 'F', 'F'], ['C', 'F', 'F', 'C']], [['C', 'F', 'F', 'C', 'F'], ['F', 'E', 'F', 'F', 'F'], ['F', 'E', 'E', 'F', 'F'], ['C', 'F', 'I_1', 'C', 'F'], ['F', 'F', 'F', 'F', 'F']]],
    "core_power": [10, 20]
}

# Generate all combinations for Loop Set 1
from itertools import product
loop_set_1_combinations = []
for combo in product(*loop_set_1_params.values()):
    run_dict = {}
    for i, (param, value) in enumerate(zip(loop_set_1_params.keys(), combo)):
        run_dict[param] = value
    # Generate description
    desc_parts = [f"{param} = {value}" for param, value in run_dict.items()]
    run_dict["description"] = " + ".join(desc_parts)
    loop_set_1_combinations.append(run_dict)

# Add to all_runs
all_runs.extend(loop_set_1_combinations)

# Loop set 2: Loop Set 2
loop_set_2_params = {
    "tank_radius": [2, 3],
    "reflector_thickness": [4, 5]
}

# Generate all combinations for Loop Set 2
from itertools import product
loop_set_2_combinations = []
for combo in product(*loop_set_2_params.values()):
    run_dict = {}
    for i, (param, value) in enumerate(zip(loop_set_2_params.keys(), combo)):
        run_dict[param] = value
    # Generate description
    desc_parts = [f"{param} = {value}" for param, value in run_dict.items()]
    run_dict["description"] = " + ".join(desc_parts)
    loop_set_2_combinations.append(run_dict)

# Add to all_runs
all_runs.extend(loop_set_2_combinations)
