"""
Run dictionaries for parametric studies.
Each dictionary entry represents a set of parameters to modify from the base inputs.
Generated by core_selection export_run_dictionaries.py
"""
import numpy as np

# Default run with base inputs
all_runs = [
    {
        "description": "Default inputs"
    }


    # Euclidean Geometric samples
    ,{
        "description": "euclidean_geometric_1",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'I_1', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'I_2', 'F', 'F', 'I_3', 'F'],
            ['C', 'F', 'F', 'I_4', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_geometric_2",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'I_1', 'F', 'F', 'F', 'F', 'I_2', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'I_3', 'F', 'F', 'F', 'F', 'I_4', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_geometric_3",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'I_1', 'I_2', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'I_3', 'I_4', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_geometric_4",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'I_1', 'I_2', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'I_3', 'I_4', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_geometric_5",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'I_1', 'I_2', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'I_3', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'I_4', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_geometric_6",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'F', 'I_1', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'I_2', 'F'],
            ['F', 'I_3', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'I_4', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_geometric_7",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'I_1', 'F', 'F', 'F', 'F', 'I_2', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'I_3', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'I_4', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_geometric_8",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'I_1', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'I_2', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'I_3', 'F', 'F'],
            ['F', 'F', 'F', 'I_4', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_geometric_9",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'I_1', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'I_2', 'I_3', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'I_4', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_geometric_10",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'F', 'I_1', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'I_2', 'I_3', 'I_4', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_geometric_11",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'I_1', 'I_2', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'I_3', 'I_4', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_geometric_12",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'I_1', 'I_2', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'I_3', 'I_4', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_geometric_13",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'I_1', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'I_2', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'I_3', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'I_4', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_geometric_14",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'I_1', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'I_2', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'I_3', 'F'],
            ['C', 'F', 'F', 'F', 'I_4', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_geometric_15",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'I_1', 'F', 'F', 'I_2', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'I_3', 'F', 'F', 'I_4', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_geometric_16",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'I_1', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'I_2', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'I_3', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'I_4', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }

    # Euclidean Lattice Geometric Diversity samples
    ,{
        "description": "euclidean_lattice_geometric_diversity_1",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'I_1', 'F', 'F', 'F', 'F', 'I_2', 'F'],
            ['F', 'F', 'F', 'I_3', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'I_4', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_lattice_geometric_diversity_2",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'I_1', 'I_2', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'I_3', 'F', 'I_4', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_lattice_geometric_diversity_3",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'I_1', 'I_2', 'I_3', 'F', 'F', 'F', 'C'],
            ['F', 'I_4', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_lattice_geometric_diversity_4",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'I_1', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'I_2', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'I_3', 'I_4', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_lattice_geometric_diversity_5",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'F', 'I_1', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'I_2', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'I_3', 'I_4', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_lattice_geometric_diversity_6",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'I_1', 'F', 'F', 'F', 'I_2', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'I_3', 'F', 'I_4', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_lattice_geometric_diversity_7",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'I_1', 'F', 'F', 'F', 'I_2', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'I_3', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'I_4', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_lattice_geometric_diversity_8",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'F', 'I_1', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'I_2', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'I_3', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'I_4', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_lattice_geometric_diversity_9",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'I_1', 'I_2', 'I_3', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'I_4', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_lattice_geometric_diversity_10",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'I_1', 'I_2', 'F', 'F', 'F'],
            ['F', 'F', 'I_3', 'I_4', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_lattice_geometric_diversity_11",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'I_1', 'I_2', 'F', 'F', 'F', 'I_3', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'I_4', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_lattice_geometric_diversity_12",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'I_1', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'I_2', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'I_3', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'I_4', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_lattice_geometric_diversity_13",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'I_1', 'F', 'F', 'F', 'F', 'I_2', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'I_3', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'I_4', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_lattice_geometric_diversity_14",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'I_1', 'I_2', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'I_3', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'I_4', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_lattice_geometric_diversity_15",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'I_1', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'I_2', 'I_3', 'F', 'F'],
            ['C', 'F', 'F', 'I_4', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_lattice_geometric_diversity_16",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'I_1', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'I_2', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'I_3', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'I_4', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }

    # Euclidean Lattice samples
    ,{
        "description": "euclidean_lattice_1",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'I_1', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'I_2', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'I_3', 'F'],
            ['F', 'F', 'F', 'I_4', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_lattice_2",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'I_1', 'I_2', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'I_3', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'I_4', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_lattice_3",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'I_1', 'I_2', 'I_3', 'F', 'F', 'F', 'C'],
            ['F', 'I_4', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_lattice_4",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'I_1', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'I_2', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'I_3', 'F'],
            ['C', 'F', 'F', 'I_4', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_lattice_5",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'I_1', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'I_2', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'I_3', 'F', 'I_4', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_lattice_6",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'I_1', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'I_2', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'I_3', 'I_4', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_lattice_7",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'I_1', 'I_2', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'I_3', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'I_4', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_lattice_8",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'I_1', 'F', 'F', 'F', 'F', 'I_2', 'C'],
            ['F', 'F', 'F', 'I_3', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'I_4', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_lattice_9",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'I_1', 'F', 'I_2', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'I_3', 'I_4', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_lattice_10",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'F', 'I_1', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'I_2', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'I_3', 'F', 'F', 'F'],
            ['F', 'I_4', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_lattice_11",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'I_1', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'I_2', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'I_3', 'I_4', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_lattice_12",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'I_1', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'I_2', 'I_3', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'I_4', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_lattice_13",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'F', 'I_1', 'I_2', 'F', 'F', 'C'],
            ['F', 'F', 'I_3', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'I_4', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_lattice_14",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'I_1', 'F', 'F', 'F', 'I_2', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'I_3', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'I_4', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_lattice_15",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'I_1', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'I_2', 'I_3', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'I_4', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "euclidean_lattice_16",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'I_1', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'I_2', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'I_3', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'I_4', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }

    # Random Geometric samples
    ,{
        "description": "random_geometric_1",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'F', 'F', 'I_1', 'F', 'I_2', 'C'],
            ['F', 'F', 'I_3', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'I_4', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "random_geometric_2",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'I_1', 'F', 'F', 'F', 'I_2', 'F', 'F'],
            ['F', 'F', 'I_3', 'F', 'F', 'I_4', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "random_geometric_3",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'F', 'F', 'F', 'I_1', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'I_2', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'I_3', 'F', 'F', 'F'],
            ['C', 'I_4', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "random_geometric_4",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'F', 'I_1', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'I_2', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'I_3', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'I_4', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "random_geometric_5",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'F', 'F', 'F', 'I_1', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'I_2', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'I_3', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'I_4', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "random_geometric_6",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'F', 'F', 'I_1', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'I_2', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'I_3', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'I_4', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "random_geometric_7",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'I_1', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'I_2', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'I_3', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'I_4', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "random_geometric_8",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'I_1', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'I_2', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'I_3', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'I_4', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "random_geometric_9",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'F', 'F', 'I_1', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'I_2', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'I_3', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'I_4', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "random_geometric_10",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'F', 'F', 'I_1', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'I_2', 'F'],
            ['F', 'I_3', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'I_4', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "random_geometric_11",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'I_1', 'F', 'F'],
            ['F', 'F', 'I_2', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'I_3', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'I_4', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "random_geometric_12",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'I_1', 'I_2', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'I_3', 'F', 'F', 'F'],
            ['F', 'F', 'I_4', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "random_geometric_13",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'I_1', 'I_2', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'I_3', 'F', 'F', 'I_4', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "random_geometric_14",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'I_1', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'I_2', 'F', 'I_3', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'I_4', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "random_geometric_15",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'I_1', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'I_2', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'I_3', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'I_4', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
    ,{
        "description": "random_geometric_16",
        "core_lattice": [
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C'],
            ['C', 'I_1', 'F', 'F', 'F', 'F', 'I_2', 'C'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'I_3', 'F', 'I_4', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
            ['C', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
            ['C', 'C', 'F', 'F', 'F', 'F', 'C', 'C']
        ]
    }
]

# Multi-parameter loops
# Generate parametric combinations automatically
# No multi-parameter loops defined
