"""
Run dictionaries for parametric studies.
Each dictionary entry represents a set of parameters to modify from the base inputs.
Generated by Parametric_GUI
"""
import numpy as np

# # Default run with base inputs
# all_runs = [
#     {
#         "description": "Default inputs"
#     },
#     {
#         "description": "fuel height change 1.0m",
#         "fuel_height": float(1.0)
#     },{
#         "description": "fuel height change 0.8m",
#         "fuel_height": float(0.8)
#     }

# ]


all_runs = [
    {
        "description": "Default inputs",
    },
    {
        "description": "Default inputs with three group energy structure",
        "energy_structure": "three_group"
    },
    {
        "description": "Default inputs with fast mode enabled",
        "fast_mode": True
    }
]
